export { default as LoginScreen } from './auth/LoginScreen';
export { default as RegisterScreen } from './auth/RegisterScreen';
export { default as CoursesScreen } from './CoursesScreen';
export { default as HomeScreen } from './HomeScreen';
export { default as NotificationsScreen } from './NotificationsScreen';
export { default as ProjectScreen } from './ProjectScreen';
export { default as SectionScreen } from './SectionScreen';
export { default as SettingsScreen } from './SettingsScreen';
export { default as VideoScreen } from './VideoScreen';
